Vagrant.configure("2") do |config|
  # Use Ubuntu 16.04 (Xenial) base box
  config.vm.box = "ubuntu/xenial64"

  # VM resources
  config.vm.provider "virtualbox" do |vb|
    vb.name = "Ubuntu 1604 LTS 64 Xenial Xerus A00"
    vb.memory = 16384
    vb.cpus = 8
    vb.customize [
        "createhd", 
        "--filename", 
        "Ubuntu 1604 LTS 64 Xenial Xerus A00.vdi", 
        "--size", 
        524288
    ]
    vb.customize [
        "storageattach", :id, 
        "--storagectl", 
        "SATA Controller", 
        "--port", 
        1, 
        "--device", 
        0, 
        "--type", 
        "hdd", 
        "--medium", 
        "Ubuntu 1604 LTS 64 Xenial Xerus A00.vdi"
    ]
  end

  # Networking
  config.vm.network "private_network", ip: "192.168.56.50"

  # Provisioning (optional)
  config.vm.provision "shell", inline: <<-SHELL
    sudo apt-get update -y
    sudo apt-get install -y curl git htop nmap
  SHELL
end